export function compactTitle(label?: string, fallback = "新会话", limit = 24) {
  const text = (label ?? "").replace(/\s+/g, " ").trim();
  if (!text) return fallback;
  return text.length > limit ? `${text.slice(0, limit).trimEnd()}…` : text;
}

/** Pi stores an icon name per session (generated by `/gui-session-meta`). */
const KNOWN_SESSION_ICONS = new Set([
  "chat-teardrop-text", "code", "image-square", "book-open", "terminal-window",
  "magnifying-glass", "list-checks", "bug", "rocket-launch", "palette", "database", "wrench",
]);

export function sessionGlyph(icon?: string) {
  return icon && KNOWN_SESSION_ICONS.has(icon) ? icon : "chat-teardrop-text";
}
